concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner"
  url = "http://gitlab-service:80"
  id = 0
  token = "your-registration-token"
  token_obtained_at = 0001-01-01T00:00:00Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "docker:19.03.13"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "73183e4f1fae"
    shm_size = 0

[[runners]]
  name = "test 1"
  url = "http://0925db94fddd/"
  id = 1
  token = "zT8yxzQMoxZui9sWAqaz"
  token_obtained_at = 2023-04-27T09:56:38Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "node"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "73183e4f1fae"
    shm_size = 0

[[runners]]
  name = "conint-1"
  url = "http://gitlab-service:80/"
  id = 3
  token = "2tyxJxc9swS_ZcWNxLis"
  token_obtained_at = 2023-06-28T11:40:28Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "node"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mode = "73183e4f1fae"
