version: "3.5"

services:
  gitlab-service:
    image: gitlab/gitlab-ce:15.5.9-ce.0
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
        gitlab_rails['initial_root_password'] = "fhtechnikumwien123"
    ports:
      - "8833:80"
      - "8822:22"
    networks:
      - gitlab-network

  gitlab-runner-service:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    depends_on:
      - gitlab-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner-config/config.toml:/etc/gitlab-runner/config.toml
    networks:
      - gitlab-network

networks:
  gitlab-network: {}
